version: '3.9'

services:
  empik_app:
    build:
      dockerfile: Dockerfile
      target: prod
      context: .
    depends_on:
      - postgres
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/requests
  postgres:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=requests